---
- name: Include prerequisites
  ansible.builtin.include_tasks:
    file: prerequisites.yaml

- name: Create values
  ansible.builtin.set_fact:
    helm_values: "{{ lookup('file', 'roles/helm-charts/files/values/' + item.name + '.yaml') | from_yaml }}"

- name: Apply pre-configurations ({{ item.name }})
  ansible.builtin.include_tasks:
    file: "../tasks/infra/{{ item.name }}.yaml"
    apply:
      tags:
        - pre-install

- name: Install release ({{ item.name }})
  community.kubernetes.helm:
    name: "{{ item.name }}"
    chart_ref: "{{ item.chart_ref }}"
    chart_version: "{{ item.version }}"
    release_namespace: "{{ item.namespace }}"
    create_namespace: false
    chart_repo_url: "{{ item.repo_url }}"
    values: "{{ helm_values }}"
    wait: true

- name: Apply post-configurations ({{ item.name }})
  ansible.builtin.include_tasks:
    file: "../tasks/infra/{{ item.name }}.yaml"
    apply:
      tags:
        - post-install