---
- name: Include prerequisites
  ansible.builtin.include_tasks:
    file: prerequisites.yaml

- name: Create values
  ansible.builtin.set_fact:
    helm_values: "{{ lookup('file', 'roles/helm-charts/files/values/' + item.name + '.yaml') | from_yaml }}"

- block:
  - name: Apply pre-configurations ({{ item.name }})
    ansible.builtin.include_tasks:
      file: "../tasks/infra/pre/{{ item.name }}.yaml"
  rescue:
    - name: Pre-install file missing, skipping
      ansible.builtin.debug:
        msg: "No pre-install task for {{ item.name }}, continuing."

- name: Install release ({{ item.name }})
  community.kubernetes.helm:
    name: "{{ item.name }}"
    chart_ref: "{{ item.chart_ref }}"
    chart_version: "{{ item.version }}"
    release_namespace: "{{ item.namespace }}"
    create_namespace: false
    chart_repo_url: "{{ item.repo_url }}"
    values: "{{ helm_values }}"
    wait: true

- block:
  - name: Apply post-configurations ({{ item.name }})
    ansible.builtin.include_tasks:
      file: "../tasks/infra/post/{{ item.name }}.yaml"
  rescue:
    - name: Post-install file missing, skipping
      ansible.builtin.debug:
        msg: "No post-install task for {{ item.name }}, continuing."