- name: Check Helm installed locally
  ansible.builtin.shell: hash helm
  delegate_to: 127.0.0.1
  run_once: true
  changed_when: false
  args:
    executable: "/bin/bash"

- name: Set action to install via Helm
  ansible.builtin.set_fact:
    deploy_action: "install"
  delegate_to: 127.0.0.1
  run_once: true
  when:
    - action is defined
    - '"install" in action'

- name: Set action to upgrade via Helm
  ansible.builtin.set_fact:
    deploy_action: "upgrade"
  delegate_to: 127.0.0.1
  run_once: true
  when:
    - action is defined
    - '"upgrade" in action'

- name: Set action to delete via Helm
  ansible.builtin.set_fact:
    deploy_action: "delete"
  delegate_to: 127.0.0.1
  run_once: true
  when:
    - action is defined
    - '"delete" in action'

- name: Set action to install issuer
  ansible.builtin.set_fact:
    deploy_action: "install-issuer"
  delegate_to: 127.0.0.1
  run_once: true
  when:
    - action is defined
    - '"install-issuer" in action'

- name: Set action to delete issuer
  ansible.builtin.set_fact:
    deploy_action: "delete-issuer"
  delegate_to: 127.0.0.1
  run_once: true
  when:
    - action is defined
    - '"delete-issuer" in action'

# - name: Install CNI
#   ansible.builtin.include_tasks:
#     file: "cni.yaml"

- name: Charts
  ansible.builtin.include_tasks:
    file: "{{ deploy_action | lower }}.yaml"
  loop: "{{ helm_charts }}"
  loop_control:
    loop_var: item

- name: MetalLB configurations
  ansible.builtin.include_tasks:
    file: "metallb.yaml"