- name: Helm pre-requisites
  tasks:
    - name: Ensure Helm repositories are present
      community.kubernetes.helm_repository:
        name: "{{ item.name }}"
        repo_url: "{{ item.url }}"
        state: present
      loop:
        - { name: longhorn, url: https://charts.longhorn.io }
        - { name: jetstack, url: https://charts.jetstack.io }
        - { name: hashicorp, url: https://helm.releases.hashicorp.com }

    - name: Update Helm repo cache
      community.kubernetes.helm_repository:
        name: longhorn
        repo_url: https://charts.longhorn.io
        update_repo_cache: yes

- name: Longhorn installation
  tasks:
    - name: Template Longhorn values
      ansible.builtin.template:
        src: values-longhorn.yaml
        dest: /tmp/values-longhorn.yaml

    - name: Install or upgrade Longhorn
      community.kubernetes.helm:
        name: longhorn
        chart_ref: longhorn/longhorn
        release_namespace: longhorn-system
        create_namespace: true
        values_file: /tmp/values-longhorn.yaml
        wait: true

- name: Template Cert-Manager values
  ansible.builtin.template:
    src: values-cert-manager.yaml
    dest: /tmp/values-cert-manager.yaml

- name: Install or upgrade Cert-Manager
  community.kubernetes.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    release_namespace: cert-manager
    create_namespace: true
    values_file: /tmp/values-cert-manager.yaml
    wait: true

- name: Template Vault values
  ansible.builtin.template:
    src: values-vault.yaml
    dest: /tmp/values-vault.yaml

- name: Install or upgrade Vault
  community.kubernetes.helm:
    name: vault
    chart_ref: hashicorp/vault
    release_namespace: vault
    create_namespace: true
    values_file: /tmp/values-vault.yaml
    wait: true