- name: Apply MetalLB IPAddressPool
  kubernetes.core.k8s:
    state: present
    # src can be relative to the role's files/ directory
    src: "{{ role_path }}/files/metallb/address-pool.yaml"
  delegate_to: 127.0.0.1
  run_once: true