---
- name: Read and base64-encode root certificate and key
  tags:
    - pre-install
  set_fact:
    rca_crt_b64: "{{ lookup('file', rca_crt) }}"
    rca_key_b64: "{{ lookup('file', rca_key) }}"

- name: Store root certificate and private key as Kubernetes secret
  tags:
    - post-install
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: root-ca
        namespace: cert-manager
      stringData:
        tls.crt: "{{ rca_crt_b64 }}"
        tls.key: "{{ rca_crt_b64 }}"

- name: Create intermediate cluster issuer
  tags:
    - post-install
  vars:
    issuer_name: intermediate-ca-issuer
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      metadata:
        name: "{{ issuer_name }}"
      spec:
        ca:
          secretName: root-ca
          # crtlDistributionPonts:
          # - "https.example.com"

- name: Create intermediate certificate
  tags:
    - post-install
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: cert-manager.io/v1
      kind: Certificate
      metadata:
        name: intermediate-ca
        namespace: cert-manager
      spec:
        isCA: true
        commonName: "mcginn.home Intermediate CA"
        secretName: intermediate-ca
        privateKey:
          algorithm: ECDSA
          size: 256
        issuerRef:
          name: intermediate-ca-issuer
          kind: ClusterIssuer

- name: Create intermediate domain cluster issuer
  tags:
    - post-install
  vars:
    issuer_name: domain-ca-issuer
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      metadata:
        name: "{{ issuer_name }}"
      spec:
        ca:
          secretName: intermediate-ca
          # crtlDistributionPonts:
          # - "https.example.com"

# Default certificate for TLS to terminate against
- name: Create domain certificate
  tags:
    - post-install
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: cert-manager.io/v1
      kind: Certificate
      metadata:
        name: domain-tls
        namespace: default
      spec:
        dnsNames:
        - "*.mcginn.home"
        secretName: domain-tls
        issuerRef:
          name: domain-ca-issuer
          kind: ClusterIssuer