apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  # Define a new server for mcginn.home on port 53
  mcginn.home.server: |
    mcginn.home:53 {
      errors
      cache 30
      # Hosts plugin can supply explicit records if you like
      hosts {
        fallthrough
      }
      # Template plugin: wildcard A record mapping any subdomain to 192.168.68.200
      template IN A *.mcginn.home {
        match ^([a-z0-9-]+)\.mcginn\.home\.$
        answer "{{.Name}} 60 IN A 192.168.68.200"
        fallthrough
      }
      # Forward any other queries upstream
      forward . /etc/resolv.conf
    }