---
- name: Wait until pods are 'Running'
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Pod
    namespace: vault
    label_selectors:
     - app.kubernetes.io/instance = vault
  register: pod_list
  until: pod_list|json_query('resources[*].status.phase')|unique == ["Running"]
  retries: 10
  delay: 10

- name: Create unseal/root key directory
  file:
    path: "{{ unseal_dir_output }}"
    state: directory
  delegate_to: localhost

- name: Initialise Vault
  kubernetes.core.k8s_exec:
    namespace: vault
    pod: vault-0
    command: vault operator init -format=json -key-shares=5 -key-threshold=3
  register: vault_init
  changed_when: "'keys' in vault_init.stdout"
  run_once: true

- name: Extract unseal keys list
  set_fact:
    vault_init_parsed: "{{ vault_init.stdout | from_json }}"

- name: Write unseal keys to files
  copy:
    dest: "{{ unseal_dir_output }}/unseal_key_{{ item.0 }}"
    content: "{{ item.1 }}"
  with_indexed_items: "{{ vault_init_parsed.unseal_keys_hex }}"
  delegate_to: localhost

- name: Write root token to file
  copy:
    content: "{{ vault_init_parsed.root_token }}"
    dest: "{{ unseal_dir_output }}/rootkey"
  delegate_to: localhost

# - name: Create a single Kubernetes Secret containing all five unseal keys + root token
#   kubernetes.core.k8s:
#     state: present
#     namespace: vault
#     definition:
#       apiVersion: v1
#       kind: Secret
#       metadata:
#         name: vault-init
#       type: Opaque
#       stringData: "{{ vault_secret_data }}"
#   run_once: true

- name: Build list of Vault pod names
  set_fact:
    pod_names: "{{ pod_list.resources | map(attribute='metadata.name') | list }}"

- name: Load all unseal keys into a list
  set_fact:
    unseal_keys: "{{ (unseal_keys | default([])) + [ lookup('file', file_item).strip() ] }}"
  loop: "{{ lookup('fileglob', unseal_dir_output + '/unseal_key_*', wantlist=True) }}"
  loop_control:
    loop_var: file_item
  delegate_to: localhost

- name: Display unseal data from file (debug)
  ansible.builtin.debug:
    msg: "{{ unseal_keys }}"

# - name: Set fact unseal_keys from loaded file
#   set_fact:
#     unseal_keys: "{{ vault_data.unseal_keys_b64 }}"
#   when: vault_data.unseal_keys_b64 is defined

- name: Unseal Vault pod with each unseal key
  kubernetes.core.k8s_exec:
    namespace: vault
    pod: vault-0
    container: vault
    command: vault operator unseal "{{ item }}"
  loop: "{{ unseal_keys }}"
  register: unseal_results
  retries: 10
  delay: 2

# Replace by somehow receiving the health check thing
- name: Verify each Vault pod is unsealed
  loop: "{{ vault_pods.resources | map(attribute='metadata.name') | list }}"
  loop_control:
    label: "{{ item }}"
  kubernetes.core.k8s_exec:
    pod: "{{ item }}"
    namespace: vault
    command: vault status -format=json
  args:
    executable: /bin/bash
  environment:
    VAULT_ADDR: "http://{{ item }}.{{ vault_release_name }}.{{ vault_namespace }}.svc.cluster.local:8200"
  register: status_results

- name: Debug pod unseal/status results
  debug:
    msg: |
      Pod {{ item.invocation.module_args.environment.VAULT_ADDR }}:
        unseal rc = {{ (unseal_results.results 
                         | selectattr('item','equalto',item) 
                         | first).rc }}
        sealed = {{ ((status_results.results 
                       | selectattr('item','equalto',item) 
                       | first).stdout 
                     | from_json).sealed }}
  loop: "{{ vault_pods.resources | map(attribute='metadata.name') | list }}"

- name: Get cluster HA status & leader
  shell: |
    vault status -format=json
  args:
    executable: /bin/bash
  environment:
    # pick any one pod, e.g. the 0th
    VAULT_ADDR: "http://{{ vault_pods.resources[0].metadata.name }}.{{ vault_release_name }}.{{ vault_namespace }}.svc.cluster.local:8200"
  register: vault_cluster_status
  changed_when: false

- name: Show HA leader info
  debug:
    msg: |
      Leader: {{ (vault_cluster_status.stdout | from_json).ha_active_node_addr }}
      Cluster size: {{ (vault_cluster_status.stdout | from_json).ha_cluster_size }}

# Installation of PKI things
# Installation of other things
# Production like seal and unseal